### ISSUE TITLE
Include Delete Item in List Actions

### ISSUE THREAD

**Issue by wegnes00** [DroopyTersen/spscript#15]
deleteItem: function (itemId) {
			    var url = baseUrl + "/items(" + itemId + ")";
			    return self.get(url).then(function (data) {
			        var item = data.d;
			        var postBody = "";
			        var customOptions = {
			            headers: {
			                "Accept": "application/json;odata=verbose",
			                "X-RequestDigest": $("#__REQUESTDIGEST").val(),
			                "X-HTTP-Method": "DELETE",
			                "If-Match": item.__metadata.etag
			            }
			        }
			        return self.post(url, postBody, customOptions);
			    });
			},
			deleteAll: function () {
			    var self = this;
			    var odata = null;
			    return getItems(odata).then(function (items) {
			        if (items && items.length && items.length > 0) {
			            for (i = 0; i < items.length; i++) {
			                self.deleteItem(items[i].Id);
			            }
			        }
			    });
			}

Example Use:

$(document).ready(function () {

    $('#DeleteItems').click(function () {
        alert("Deleting..");
        var siteUrl = _spPageContextInfo.webAbsoluteUrl;
        var listSvc = new SPScript.RestDao(siteUrl);
        var listItemId = $('#ListItemIds').val();
        var listName = "Warranty Pictures";

        var deleteListItemRequest = listSvc.lists(listName).deleteItem(listItemId);
    });
});

<!div> 
   <!input name="ListItemIds" id="ListItemIds" type="text"/>
   <!br/>
   <!input id="DeleteItems" type="button" value="Delete Items"/> 
​​​<!/div>

**Comment by DroopyTersen** [comment]
Sweet! Thanks, all set and tested
https://github.com/DroopyTersen/spscript/blob/v1/src/list.js
![image](https://cloud.githubusercontent.com/assets/4020046/6535776/2f3d12a6-c40d-11e4-98d2-4cc42809c987.png)
