### ISSUE TITLE
CrossDomainDao Cannot Make Valid Request with .lists, .getItems and Query Options

### ISSUE THREAD

**Issue by wegnes00** [DroopyTersen/spscript#23]
**Example Error**

var profileListRequest = profileListSvc.lists(profileListName).getItems(profileListQueryOptions)
                                  .then(setProfilePanel);

**Creates this error**
GET https://w03-af00dcc3adbdac.sharepoint.com/FormsApp/_api/SP.AppContextSite(@…le('Profiles')/items?$select=Title@target=%27https://w03.sharepoint.com%27 400 (Bad Request)

error: {code: "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",…}}
error: {code: "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",…}
code: "-1, Microsoft.SharePoint.Client.InvalidClientQueryException"
message: {lang: "en-US", value: "The expression "Title@target='https://w03.sharepoint.com'" is not valid."}
lang: "en-US"
value: "The expression "Title@target='https://w03.sharepoint.com'" is not valid.

**In SPSCRIPT.JQUERY.JS** 
this.scriptReady.done() has a variable that sets the '@target' in the full url
var executor = new SP.RequestExecutor(self.appUrl),
                fullUrl = self.appUrl + "/_api/SP.AppContextSite(@target)" + hostRelativeUrl + "@target='" + self.hostUrl + "'";

**Using the following '.get' does NOT produce this error** But it also does not call additional query options
    var profileListRequest = profileListSvc.get(profileListUrl)
                                .then(setProfilePanel);

**Comment by DroopyTersen** [comment]
haven't done an app that needs the cross domain dao in years. going to write this one off
