### ISSUE TITLE
Upload attachment to sharepoint list

### ISSUE THREAD

**Issue by rizkyramadhan** [DroopyTersen/spscript#29]
Hi

It would be nice if we can upload attachment to sharepoint list

**Comment by rizkyramadhan** [comment]
I just wrote pull request regarding this. 
https://github.com/DroopyTersen/spscript/pull/30

**Comment by DroopyTersen** [comment]
Thanks for the help! Pull request is merged.  I'm going to create a separate issue for myself to update the documentation.
