### ISSUE TITLE
How To Do Cross Domain Request?

### ISSUE THREAD

**Issue by BosNaufal** [DroopyTersen/spscript#39]
Hey @DroopyTersen, Thank you for making this awesome library. 

I would like request data over the cross-domain site, how could I do that? Is there any example or documentation about it? I'm just wondering How To Do Cross Domain Request?

I've been trying using your crossDomainDao.js but it seems not work. it throws an error that said `"There is no app context to execute this request."`

**Comment by DroopyTersen** [comment]
@BosNaufal - Can you give me a little background on your use case? (Provider vs SharePoint Hosted App, O365 vs OnPrem etc...).   High level, the CrossDomainDao will only work if you've first registered your app with SharePoint to allow the Cross Origin trust.

The crossDomainDao is also a remnant from an old version of SPScript that I haven't updated and merged into the new build or documented yet (I plan to, I've just been waiting until I need to do it for work). If you've got a need I should be able to knock it out pretty quick.

Feel free to jump on the Gitter chat, for more realtime feedback.
https://gitter.im/DroopyTersen/spscript
