### ISSUE TITLE
Cant get it working for IE9

### ISSUE THREAD

**Issue by mubaid** [DroopyTersen/spscript#60]
Hey! All seems ok on most modern browsers, except IE9?
I am suspecting this is related to the then() / promise implementation?

A simple call like this doesn't show any errors in the console but nothing happens either:

var dao = new SPScript.RestDao();
var list = dao.lists("MyList");
//works till here, next line nothing happens. no errors in console either.
list.getItems().then(
function(items){
  console.log(items)  
})

Can you confirm this issue? 
I am using this for SharePoint 2016 On-Prem on Windows 7, IE9.

Thanks.

**Comment by DroopyTersen** [comment]
Hi there @mubaid . It theoretically should work fine in IE9 (there is a Promise polyfill embedded in the SPScript distribution build).  I don't have access to a machine with IE9, but I did verify my tests with IE11 in IE9 document mode.  

There is a funky issue in IE9 where console.log doesn't work unless you have F12 DevTools open.  To try to see your errors, you can tack a `.catch()` onto your Promise chain like so:

``` javascript
var dao = new SPScript.RestDao();
var list = dao.lists("MyList");
//works till here, next line nothing happens. no errors in console either.
var promise = list.getItems()
//Make sure you have a valid Promise object here
console.log(promise);
//handle promise resolution
promise.then(function(items){
        console.log(items)
    })
    .catch(function(err) {
         console.log(err)
    })
```

**Comment by mubaid** [comment]
Thanks, here is the error msg 

"TypeError: Unable to get value of the property 'd': object is null or undefined"

On checking with Fiddler and the Network tab, I see that the web service call was fine, and the data was retrieved.
Any thoughts?

**Comment by DroopyTersen** [comment]
hmmm @mubaid  okay nice yes i was able to replicate. I'll work on this today and keep you posted.

**Comment by DroopyTersen** [comment]
@mubaid found the problem. patch coming shortly

**Comment by mubaid** [comment]
Awesome, I was debugging the script and found the cause too. Apparently changing the xhr.response to xhr.responseText seems to be working. I have tested this with IE9 and chrome. However, you are the best judge here!

**Comment by DroopyTersen** [comment]
@mubaid you were spot on. IE9 uses responseText instead of response.   I was able to replicate then resolve.  Take her for a spin. Make sure you grab version 2.0.1

**Comment by mubaid** [comment]
@DroopyTersen I just merged your changes with the existing version we had. We are using your templating engine which breaks our code on the 2.0.1 since its removed.
Can we have 2 versions of SPScript? 1 with template engine and the other without?
Thanks for your help!

**Comment by DroopyTersen** [comment]
@mubaid haha i agonized over removing that for the 2.0 release. do you know which version # you are using? If you used npm to get SPScript it will be in its package.json.  

Also, you might be able to get away with using 2.0.1 and setting SPScript.templating = require ("mustache")

**Comment by mubaid** [comment]
@DroopyTersen I had directly used the js from dist, so we are on v1 I believe? I am not sure though.

**Comment by mubaid** [comment]
@DroopyTersen I upgraded to V2.0.1 and used mustache.js and modified our code to use mustache rather than SPScript templating. Works like charm.
Thanks a ton for all your help!
