### ISSUE TITLE
ReferenceError XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by bitscompagnie** [DroopyTersen/spscript#66]
Hello,

I just discovered your module and was trying to test it in node.js v1.13.1 on Windows 7, but I keep getting below error:

I am able to get the following line without error: 
```
var dao = new SPScript.RestDao(siteUrl);
console.dir(dao);
```

But when I try the sample code:

```
var taskList = dao.lists("Tasks");

// BEST: Option 1 - 'Find' syntax sugar
taskList.findItems("Status", "Completed").then(logApprovedTasks);
// BETTER: Option 2 - OData support in the '.items()'
taskList.getItems("$filter=Status eq 'Completed'").then(logApprovedTasks);
// GOOD: Options 3 - Manual 'GET'
dao.get("/web/lists/getByTitle('Tasks')?$filter=Status eq 'Completed'").then(function(data) {
    if (data && data.d && data.d.results) {
        logApprovedTasks(data.d.results);
    }
});
var logApprovedTasks = function(tasks) {
    tasks.forEach(function(task) {
        console.log(task.Title);
    });
};
```

```
ReferenceError: XMLHttpRequest is not defined
    at ajax (C:\git\spdevscript\node_modules\SPScript\lib\ajax.js:53:16)
    at BaseDao.RestDao.executeRequest (C:\git\spdevscript\node_modules\SPScript\lib\restDao.js:4
2:9)
    at BaseDao.get (C:\git\spdevscript\node_modules\SPScript\lib\baseDao.js:43:14)
    at Object.<anonymous> (C:\git\spdevscript\app.js:15:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```
Thanks for your help.

**Comment by DroopyTersen** [comment]
Because you can't authenticate through the browser, there is a little setup involved.  You also will use the ServerDao instead of SPScript.RestDao.

1. Register a SharePoint app using "_layouts/15/appregnew.aspx ".  Make note of your clientId and clientSecret
2. Grant your new app permissions using "_layouts/15/appinv.aspx".  You can use the xml snippet below to grant site collection admin access.  The key part is you set `AllowAppOnlyPolicy` to true.
``` xml
  <AppPermissionRequests AllowAppOnlyPolicy="true" >
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
  </AppPermissionRequests>
```
3. Switch from a RestDao to a ServerDao.  (This isn't exposed by default at the moment so you have to grab it the long way).   Fill in the values from step 1 and the snippet below should work.

``` javascript
// Your path to node_modules may be different
var ServerDao = require("../node_modules/spscript/server/serverDao");

const SITE_URL = "INSERT_VALUE";
const CLIENT_ID = "INSERT_VALUE";
const CLIENT_SECRET = "INSERT_VALUE";
var dao = new ServerDao(SITE_URL, CLIENT_ID, CLIENT_SECRET);

var taskList = dao.lists("Tasks");

// BEST: Option 1 - 'Find' syntax sugar
taskList.findItems("Status", "Completed").then(logApprovedTasks);
// BETTER: Option 2 - OData support in the '.items()'
taskList.getItems("$filter=Status eq 'Completed'").then(logApprovedTasks);
// GOOD: Options 3 - Manual 'GET'
dao.get("/web/lists/getByTitle('Tasks')?$filter=Status eq 'Completed'").then(function(data) {
    if (data && data.d && data.d.results) {
        logApprovedTasks(data.d.results);
    }
});
var logApprovedTasks = function(tasks) {
    tasks.forEach(function(task) {
        console.log(task.Title);
    });
};
```

**Comment by DroopyTersen** [comment]
I should have also noted, the OAuth dance outlined above will only work in Office 365. If you are on-prem you are unfortunately out of luck from a Node/SPScript perspective.

**Comment by bitscompagnie** [comment]
Thanks for your reply. I am on-prem. 

I have now started using the code in a simple aspx page on my site. 

```
var taskList = dao.lists("Tasks");

// BEST: Option 1 - 'Find' syntax sugar
taskList.findItems("Status", "Completed").then(logApprovedTasks);
var logApprovedTasks = function(tasks) {
    tasks.forEach(function(task) {
        console.log(task.Title);
    });
};
```

Is there any special setup to get the above code work? I was expecting to see list of tasks.

Currently testing the code and have found that the following snippet works great:
```
dao.search.query('name1').then(function(searchResults) {
    searchResults.items.forEach(function(item) {
        console.log('Search result: ' + item.Title);
    });
});
//Get the current user's profile properties
dao.profiles.current().then(function(profile) {
    var fullName = profile.FirstName + ' ' + profile.LastName;
    var docTitle = profile.Title;
    console.log(fullName + '\n Job title: ' + docTitle);
});

dao.search.people('name2').then(function(result) {
    result.items.forEach(function(item) {
        //Find the name of users
        console.log(item.PreferredName)
    });
});
```
Thanks so much.

**Comment by bitscompagnie** [comment]
Never mind my last message. I got the code working on my test list.

I hope you will find a time to post a real world example.

This looks definitely very promising.

Thanks for this module.

**Comment by DroopyTersen** [comment]
Do you have suggestions for real world examples that would be valuable?

**Comment by bitscompagnie** [comment]
Hello again,

An example of an app that fetches list items displays them on a page. The app could have the following features: create, update, search list items and display them (with hyperlinks to the items themselves). It could also add one attachment or multiple attachments to an item.

If the app can integrate a good site navigation that will be good.

Those are some ideas that come to mind.

Thanks a lot.
