### ISSUE TITLE
How to query a list view items?

### ISSUE THREAD

**Issue by bitscompagnie** [DroopyTersen/spscript#67]
Hello,

How can we query a list view using spscript? I have see the following: [How to get all items in a view using REST API](https://sharepoint.stackexchange.com/questions/135936/how-to-get-all-items-in-a-view-using-rest-api) and was trying to use spscript to get all list view items.

Thanks for your help.

**Comment by DroopyTersen** [comment]
The SharePoint REST Api (and SPScript) use [OData](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/) as the primary query language.  SP Views on the other hand are driven by CAML.  So typically, I would "recreate" my list view using OData. 

For example, if I had a Task list view that showed the most recent completed tasks, I wouldn't monkey with CAML, I'd write the following Odata

``` javascript
var dao = new SPScript.RestDao();
dao.lists("Tasks").getItems("$filter=Status eq 'Complete'&$orderby=Modified desc")
    .then(items => console.log(items));
```

As an alternative, there is a way make a POST request and pass CAML (which you'd get from your View).  You could use dao.post() in conjunction with what this article describes: https://chuvash.eu/2014/03/25/using-caml-with-sharepoint-rest-api/

**Comment by bitscompagnie** [comment]
Thanks a lot,

I will try the second option.

Do you have any working example of dao.post()?

**Comment by DroopyTersen** [comment]
Yeah there is an example the uses dao.post to update the site logo url https://github.com/DroopyTersen/spscript#get--post-requests

**Comment by bitscompagnie** [comment]
Thanks, I will try it to get list view items.

**Comment by bitscompagnie** [comment]
I have the following function and it is only getting the caml output and not the actual field values.

```
function getListViewDataCamlREST(siteUrl, listName, viewTitle, caml) {
    var dao = new SPScript.RestDao(siteUrl);
    var viewXml = '<View><Query>' + caml + '</Query></View>';
    dao.getRequestDigest() // get the auth token
        .then(SPScript.headers.getUpdateHeaders) // add the token to request headers 
        .then(function(headers) {
            // create a manual post request
            // var endpoint = "/_api/web/lists/GetByTitle('" + listName + "')/GetItems";
            var requestData = {
                "query": {
                    "__metadata": { "type": "SP.CamlQuery" },
                    "ViewXml": viewXml
                }
            };
            var body = requestData; //{ __metadata: { "type": "SP.Web" }, SiteLogoUrl: siteLogoUrl };
            return dao.post("/web/lists/getByTitle('" + listName + "')/Views/getbytitle('" + viewTitle + "')/ViewQuery", body, { headers: headers })
        })
        .then(function(result) {
            console.log(result);
        })
        .catch(function(error) {
            console.log("Something wrong happened: " + error);
        })
}

var caml = "<Where><Or><FieldRef Name='Teamone'/><Value Type='Text'>Project one</Value></Eq></Or></Where>";
getListViewDataCamlREST(siteUrl, 'My Project', 'All Items', caml);
```
The above is giving me the following result, which should be the field values instead:

`"<GroupBy Collapse="FALSE" GroupLimit="30"><FieldRef Name="group" /></GroupBy><OrderBy><FieldRef Name="group" /><FieldRef Name="Status" /></OrderBy><Where><And><And><And><And><And><Eq><FieldRef Name="Title" /><Value Type="Text">Project one</Value></Eq><Eq>    <FieldRef Name="Status" /><Value Type="Text">Closed</Value></Eq></And>    <Geq><FieldRef Name="DateClosed" />    Value Type="DateTime">2014-10-01T00:00:00Z</Value></Geq></And>    <Leq><FieldRef Name="DateClosed" />    <Value Type="DateTime">2015-09-30T00:00:00Z</Value></Leq></And>    <Neq><FieldRef Name="group" />    <Value Type="Text">Group one</Value></Neq></And><Neq>        <FieldRef Name="group" /><Value Type="Text">Group two</Value></Neq></And></Where>"`

Any idea about how to get the proper values?

**Comment by DroopyTersen** [comment]
The code you posted is actually working as expected.  Whats happening is you have the wrong endpoint api url. 

This line is actually saying "*hey, find this view, on this list, and give me the view xml*" (instead of "*hey, query this list, using this caml*" ).
``` javascript
return dao.post("/web/lists/getByTitle('" + listName + "')/Views/getbytitle('" + viewTitle + "')/ViewQuery", body, { headers: headers })
```
The url you actually want to post to is:
``` javascript
"/_api/web/lists/GetByTitle('" + listName + "')/GetItems"
```

That being said, the CAML in your example is pretty simple.  If it were me, I'd just do this instead:
``` javascript
var dao = new SPScript.RestDao();
dao.lists("My Project").getItems("$filter=Teamone eq 'Project one'")
   .then(function(items) {
        console.log(items);
   })


```
A second, even simpler option in this "*find all items by a specific field value*" scenario is:
``` javascript
dao.lists("My Project").findItems("Teamone", "Project one")
   .then(function(items) {
        console.log(items);
   })
```

If you are still stuck using CAML, the following function should be what you're after:
``` javascript
var getItemsByView = function(listName, viewName, siteUrl) {
    var dao = new SPScript.RestDao(siteUrl);
    var listUrl = "/lists/getByTitle('" + listName + "')"
    var viewUrl = listUrl + "/Views/getByTitle('" + viewName + "')/ViewQuery"
    // 1. Get the targeted view on the targeted list so we can pull out the ViewXml
    return dao.get(viewUrl)
  	 .then(SPScript.utils.validateODataV2)
  	 .then(function(view) {
             // Now that we found the view, craft a POST request the the /GetItems endpoint
    	     var queryUrl = listUrl + "/GetItems";
    	     var postBody = { 
                 query : {
        	     "__metadata": {
          	         type: "SP.CamlQuery"
        	     },
        	     ViewXml: view.ViewQuery
      	         }
              };
              // Use an SPScript helper to authorize your POST so 
              // you don't have to mess with Auth headers
              return dao.authorizedPost(queryUrl, postBody)
  	})
        .then(SPScript.utils.validateODataV2)
  	.then(function(items) {
    	     console.log(items);
  	});
};

//Example Usage (third param, siteUrl, is optional, it will use current site if you don't pass it
getItemsByView("My Project", "All Items")
```

**Comment by DroopyTersen** [comment]
I am working on SPScript 3.0.  I think I am going to add a `dao.lists("My List").getItemsByView(viewName)` method so I never have to write that code again ;)

**Comment by bitscompagnie** [comment]
Hello again and thanks for your reply. I have used the function you posted and it does not give a particular error, but instead of returning the fields in the list view, it is returning all the fields from the list itself. Am I doing something wrong? I maybe tired now.

Add the list view query method to version 3.0 will be really helpful. 

Thanks a lot.

**Comment by bitscompagnie** [comment]
I ended up taking your advice in using SPScript with date filtering to get the data I was after.
Thanks again for this great module.
