### ISSUE TITLE
Enhancement - Sending Email using Rest API?

### ISSUE THREAD

**Issue by mubaid** [DroopyTersen/spscript#69]
@DroopyTersen 
Can we add a method to send email using the Rest API endpoint `_api/SP.Utilities.Utility.SendEmail`
This will simplify sending simple emails like alerts / notifications etc via the Rest API.

Something on these lines is mentioned here: 
[https://sharepoint.stackexchange.com/questions/148226/send-e-mail-from-javascript-using-rest-api](url)

However, I am not sure it works on SPO - some people are complaining the emails isn't being sent out on SPO.

**Comment by DroopyTersen** [comment]
Hello, sorry for the very delayed response. If you are still out there, I would recommend you take a look at using SPScript's built in `ctx.authorizedPost` to achieve this.  It's a generic helper for anytime you want to make a POST request to the rest api that includes the Request Digest for authorization.

I've never actually played with the `SP.Utilities.Utility.SendEmail` endpoing in SP Online, but if it does work, the code with `authorizedPost` would look something like this:

*I haven't actually tried this, I just took the stackoverflow answer from your link and SPScriptified it*
``` typescript
let ctx = SPScript.createContext("https://yourtenant.sharepoint.com/sites/yoursite");
let payload = {
        'properties': {
            '__metadata': {
                'type': 'SP.Utilities.EmailProperties'
            },
            'From': ["a@b.com","b@b.com"],
            'To': {
                'results': ["c@c.com","d@d.com"]
            },
            'Body': "Hi there",
            'Subject': "From SPScript"
        }
    }
ctx.authorizedPost("/_api/SP.Utilities.Utility.SendEmail", payload)
```
