### ISSUE TITLE
Update lookup field

### ISSUE THREAD

**Issue by nickidk4** [DroopyTersen/spscript#74]
I am trying to update a field with multiple lookup values.
Would love to see a code example with this.

**Comment by DroopyTersen** [comment]
Hello sorry for the delayed response, it should be something like this:
``` typescript
let ctx = SPScript.createContext("https://yourtenant.sharepoint.com/sites/yoursite");
// Store the lookup ids as a Number array
let newLookupIds = [ 12, 45, 24 ];
// use the lookup ids to create an updates object, Categories is my multivalue lookup column
let updates = {
  CategoriesId: { results: newLookupIds }
}
// Update the item whose ID is 3
await ctx.lists("Notifications").updateItem(3, updates);
```


I'm in the process of converting converting SPScript tests from Mocha to Jest so I'll put a todo to write a test for updated multi-value lookup columns to verify
