### ISSUE TITLE
SPScript download link is broken

### ISSUE THREAD

**Issue by ebitsdev** [DroopyTersen/spscript#82]
Hello @DroopyTersen,

The download link under option 2 is apparently broken: https://raw.githubusercontent.com/DroopyTersen/spscript/typescript/dist/v3/spscript.js

Can you please check it?

Thanks,

**Comment by DroopyTersen** [comment]
Sorry about that.  I want to switch to use `unpkg` for serving up assets.  Unpkg is actually meant for this purpose where as `raw.githubusercontent.com` sometimes doesn't set mime types properly and isn't optimized as a CDN.

[https://unpkg.com/spscript@3.1.0/dist/v3/spscript.js](https://unpkg.com/spscript@3.1.0/dist/v3/spscript.js)

I'll update the docs to include the above link.

I'm working on a 4.0, which is a total rewrite of the packaging mechanism. Currently I don't have a 4.0 version that gets built as a fully bundled browser ready file (that can be included via `script` tag).  At the moment, 4.0 assumes you have some sort of build process (like webpack).  As soon as I have it I'll update the docs to point at at `unkpg` serving the 4.0 bundle.

**Comment by ebitsdev** [comment]
Thanks a lot.
I really appreciate the efforts.

**Comment by DroopyTersen** [comment]
@ebitsdev  I've updated SPScript to get packaged up with much cleaner UMD bundle.

[https://unpkg.com/spscript@4.1.0/dist/spscript.js](https://unpkg.com/spscript@4.1.0/dist/spscript.js)
